server:
  port: 8444

spring:
  application:
    name: poc
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 36000000
      refresh-token:
        expiration-time: 604800000
    user:
      name: develop
      password: p@ssw0rd!!